---
title: "Scrape Katia"
author      : J. Luis Juncal
date        : 2017-09-19
output: html_notebook
---



```{r Carga de librerías, echo=FALSE}
library(dplyr) # básico, cárgoo  por costume
library(rvest) # carga automáticamente xml2
library(readr) # para as operacións con ficheiros
library(data.table) # só se usa unha vez
library(stringr) # para as operacións con cadeas

```

Ler o ficheiro a rechear 

```{r Lectura de ficheiro con readr}
listado_de_productos_prestashop <- read_delim("~/XornadasR/listado de productos prestashop.csv", ";", escape_double = FALSE, trim_ws = TRUE)
```

Scrape katia using ##rvest## utilities

```{r Scraper inicial}
# Procesado da páxina principal, é distinta ás páxinas onde estará a información. 
# Poderiamos coller o campo prezo aquí, máis por sinxeleza e seguridade farémolo todo na mesma función

url<-read_html("http://www.katia.com/ES/lanas.html")
lanas<-url%>% 
        html_nodes("#principal .txt_normal .txt_normal")%>%
        html_text()

url%>%html_nodes('#principal .txt_normal .txt_normal')%>%
        html_attr("href")->enlaces_lanas
##crear data.table temporal
tabla_enlaces<-data.table(lanas,enlaces_lanas)
head(tabla_enlaces)
```



Next, we have to iterate over the table, and scrape the links in it.
```{r Función Scraper}
scrape_katia <- function(url_to_scrape) {
        
        scraped_url <- read_html(url_to_scrape) # Ler só unha vez, moi importante
        
        
        #Código de precio funcional
        
        precio <- scraped_url %>%
                html_nodes("#principal b") %>% html_text()
        
        #Código do nome funcional
        nome<-scraped_url%>%
                html_nodes(".titol_modrev_mini_new")
        
        nome<-nome[1]%>%html_text()%>%
                str_replace(precio,"")# Exemplo de acceso por código, non por CSS Selectors
        
        # Código das imaxes funcional
        # vamos falar dos scripts na páxina
        # obtemos unha lista de caracteres
       imaxes<-scraped_url %>%
        html_nodes("#gal1 .llistatcolors")%>%html_attr("data-image")
       
        Sys.sleep(1) # importante, sen isto podería causar un DOS
      
      taboa_temp<-data.table(nome,precio,imaxes) # as.data.table(c(nome,precio,imaxes)) daría como resultado un matriz 16x1
      # taboa_final<<-rbindlist(list(taboa_final,taboa_temp))
      head(taboa_temp)
        return(taboa_temp)
      
       
}


taboa_final<-lapply(tabla_enlaces$enlaces_lanas,scrape_katia) #produce unha lista, executar con coidado que é moi lenta
taboa_final<-Reduce("rbind",taboa_final) # converte a lista en taboa
head(taboa_final)
write.csv2(taboa_final,file = "taboa_final.csv")
```